Below, I've listed my favourite writing from the [previous incarnation of this website](https://coveredinbees.org.archived.website/), coveredinbees.org (named as a hat-tip to emergent systems, essential to the PhD). You'll find writing about what forms of human organisation are possible; various economic, spatial and methods ideas; posts on climate; stuff about visualisation and data; and a [long list of](#coveredinbees-curiosities) other little curiosities.

## [Best of Coveredinbees](https://coveredinbees.org.archived.website/)

- **[Three adaptive landscapes](https://coveredinbees.org.archived.website/3adaptivelandscapes.html)**: how humans are natural distributed systems makers, what Balinese rice pest management, Peruvian potato growing and the market economy have in common, why it's all tangled up with magic and why it means Hayek was wrong.
- **["At last, the people!" Stafford Beer's model of the Chilean economy](https://coveredinbees.org.archived.website/node/165.html)**. Via [this UMIST lecture](https://www.youtube.com/watch?v=e_bXlEvygHg) by Beer, a discussion of how he understands the role of economic data ("algedonics") in his [Cybersyn](https://en.wikipedia.org/wiki/Project_Cybersyn) system. Mulling Beer and Hayek's opposite views on how to guarantee freedom: Stafford Beer believes you can "design for freedom", Hayek believes human design is precisely the thing that ends freedom. "Beer argues that the machinery of freedom is built into his system, just as Hayek argues it's woven into our evolved institutions. So why can it be built into the machinery of institutions, but not the machinery of machinery?" (Overlaps with the [socialist economic calculation debate](https://en.wikipedia.org/wiki/Socialist_calculation_debate).)
- **[Economics: reform or revolution](https://coveredinbees.org.archived.website/node/485.html)**? How building an economic model for the PhD changed my view of economic methods and micro-economics, and why it's made me unsympathetic to attacks on caricatured versions of economics. As I say in a different post, "That's annoying, wrong and that used to be me."
- **[Cars shape places. So what will places look like in a hundred years' time](https://coveredinbees.org.archived.website/node/438.html)**? Bouncing off a Glaeser quote showing how radically the car transformed city layout (from hub/spoke to something much more decentralised and spread out). So, what will happen as we transition to zero carbon? Maybe historical examples – like how containerisation radically re-wired port cities, including Liverpool – might help.
- **[What's the difference between a box-plot and an x-ray](https://coveredinbees.org.archived.website/node/403.html)**? Why understanding what our brains bring to visualisation is so important. X-rays require a tonne of guided training before you can see anything at all. Boxplots need some training, but with a little application can make sense fairly quickly. Infographics have the specific goal of communicating clearly to an untrained lay audience. Also talks about how visualisation for personal comprehension (e.g. making a mindmap, which will make zero sense to an outsider) is useful, but can lead visualisers to misunderstand what others can see in a viz.
- **[Economic self-organisation: at home in humans.](https://coveredinbees.org.archived.website/adaptivelandscapes2.html)** Hayek insisted that the discovery of the price system was borderline miraculous, and saw claims that we could design better as no more sane than a termite saying they had a blueprint for a better mound. But there's a parallel to how our vision of the emergence of life has shifted from "near-impossible" to [Kauffman's picture](http://web.stanford.edu/class/symbsys205/Kauffman.htm) of life being "at home in the universe", built right into the mathematics of self-organisation. In this vision, life emerges right out of the logic the universe runs on. We sorely need that same collective sense in how we view human organisation. Bonus Jane Jacobs / Elinor Ostrom, and discussion of the difference between evolutionary and economic meanings of efficiency.
- **[Utility is useful and planets don't love each other](https://coveredinbees.org.archived.website/node/382.html)**: using an example from transport economics ("savings in walking and waiting times are valued at between two and three times savings in on-vehicle time – parameters that have proved to be remarkably robust over the years") to argue that utility theory is super-useful *for the level of explanation it works at* and doesn't need any extra explanatory juice. E.g. "Pinning utility onto rationality is not necessary – any more than the theory of gravity requires planets to love each other." This in no way stops anyone from digging deeper if required.
- **[Humans: nought but shipping containers that need to sleep at night](https://coveredinbees.org.archived.website/node/476.html)**: "Humans can be value dense, just like anything else you shift on a truck and back into a factory. But, as production inputs, they have some idiosyncracies that set them apart from coal or crankshafts or hard drives…" Why the concept of value density is super-useful in spatial economics (despite seemingly only being used in logistics). It's useful for understanding why Glaeser-style arguments about the irrelevance of transport costs aren't uniformly true (e.g. it depends on the point in logistics chains; earlier points – raw materials, say – are less value dense and distance is much more important).
- **["Moloch, whose blood is running money!" Can supra-human systems have intention?](https://coveredinbees.org.archived.website/node/477.html)** Includes ponderings on an evolving boids model I made that seemed to produce intention & Pollan's point that humans are just "pawns in corn's clever strategy to rule the Earth". "This notion that emergence or corn or money might have its own agenda helps explain why 'just stopping' might be beyond us. We are not sovereign."
- **[How economics avoids comparing rich and poor](https://coveredinbees.org.archived.website/node/471.html)**: Pareto optimality, the moment much of economics stopped doing welfare comparisons, and why keeping the concept of utility simple – it's just a tool – should allow us to e.g. understand why diminishing returns can apply to comparative wealth (7% drop in income: for some people, skip meals, for others, skip one of three foreign holidays)
- **[Climate change: melting ideologies](https://coveredinbees.org.archived.website/node/481.html)**. "If climate change straightforwardly slots into your existing political worldview, you're not questioning that worldview enough and you're probably alienating a bunch of people in the process. To the extent that climate change becomes umbilically linked to the victory of one particular worldview, that stuffs any real chance of genuine dialogue to solve it." This is more of a provocative statement – I'm not sure I fully believe my own argument here. But I think it's at least half right. I also think it's important to accept there will continue to be arguments about climate change stemming from genuinely held beliefs, and we need to work hard to keep them civil (while also blocking trolls, deniers and [predatory delayers](https://twitter.com/alexsteffen/status/902164491651006464?lang=en-GB)).
- **[Is language more like a logic machine or more like ant pheromone trails](https://coveredinbees.org.archived.website/node/474.html)**? "Language didn't evolve as a tool for understanding the world, in the way we usually think of it, any more than [ant pheromone trails](http://icouzin.princeton.edu/pheromone-trail-networks-in-ants/) did. So there's actually no *a priori* reason to expect a venn diagram of language and logic to have any overlap." Part of thinking about what the full state space of possible human organisation could be (with a dollop of "It's life Jim, but not as we know it.")
- **[Would "development without material growth" still show up as economic growth?](https://coveredinbees.org.archived.website/node/458.html)** "A rainforest might be \`steady-state' but it's ever-evolving. And actually, human development – while sharing some characteristics of evolving systems – has its own dynamic that's more a mash-up of attentive artistry and evolution. Which leads me to worry about building an entire political theory around an abstract target of zero-growth." Includes a scary stat from [Jorg Friedrich](https://www.timeshighereducation.com/books/the-future-is-not-what-it-used-to-be-climate-change-and-energy-scarcity-by-jrg-friedrichs/2007555.article): assuming 3% per annum growth would require the resource intensity of the economy by 2100 to be reduced by 95% if resource levels were to be kept as they are today (so, cutting resource intensity is even harder).
- **["Actively seek out new opportunities to feel stupid"](https://coveredinbees.org.archived.website/node/425.html)**: That's a quote from Martin A. Schwartz's [The Importance of Stupidity in Scientific Research](https://journals.biologists.com/jcs/article/121/11/1771/30038/The-importance-of-stupidity-in-scientific-research). He also says: "If we don't feel stupid it means we're not really trying". This post explores his idea of 'productive stupidity', connects it to probing the dark beyond the [streetlights](https://en.wikipedia.org/wiki/Streetlight_effect) we usually work under and why writing is such a vital exploration tool.
- **[Can a Tralfamadorian make predictions](https://coveredinbees.org.archived.website/node/483.html)**? How ontogical predictions (like discovering Neptune from oddities in the orbits of other planets) differ from forecasts, and why it matters for one of the most common critiques of economics.
- **[The social technology of drug production: can we do better](https://coveredinbees.org.archived.website/node/301.html)**? A discussion of the social structures that currently produce pharmaceutical goods, with a comparison to the incentives of open source production. "'Cost is an incentive mechanism' is, in and of itself, not wrong of course – the error comes in claiming it's all there is."
- **[The tension between searching for universal human traits and making humans fit our model of the world](https://coveredinbees.org.archived.website/node/257.html)**. Many free market thinkers have searched hard to establish the free market human as natural. At the same time, others have said any non-market traits need to be educated out of us (including Hayek, who thought we were born with "socialistic" instincts that needed removing). This affects how we should think about the quantitative and economic models we build. Includes a quote from Senator Henry Dawes after visiting the Cherokee in 1885: "Yet the defect of the system was apparent. They have got as far as they can go because they own their land in common. It is Henry George's system, and under that there is no enterprise to make your home any better than that of your neighbours. There is no selfishness, which is at the bottom of civilisation." [Related post](https://coveredinbees.org.archived.website/node/180.html) on arguments about how far science can put bounds on the nature of the economic human, and how similar ideas were used by the UK's Conservative Party.
- **[If internet monopoly logic applied in meatworld](https://coveredinbees.org.archived.website/node/464.html)**. "Want to set up a local grocery store? Well, you can't. You can grow produce, but it must be posted to a centralised distribution centre, owned by The Global Greengrocer Company and – after being sold in their own store and taking 30% of the revenue – they'll send you some cash." Plus discussion of how the power of companies like Google could radically change what roads look like.
- **[When Systems go Cargo Cult](https://coveredinbees.org.archived.website/node/406.html)**. Whether it's 'market forces' (working in natural monopolies like water supply *how?*) or blind faith in the democratising, knowledge-improving power of the internet, it's easy to forget we need to *understand*, tend to and design systems, not just pray to them. "It's like turning up to some vital, knife-edge diplomatic negotiation teetering on the edge of war, cracking open a beer and saying, \`chill – language will save us.' "
- **[How are "costs" defined](https://coveredinbees.org.archived.website/node/384.html)**? And why does the answer make me question utopian visions of local food production? (And is that a worrying side-effect of having imbibed too much neoclassical economic koolaid?)
- **Genetic modification of crops: the science is clear, it's not inherently dangerous. So why is there so much opposition**? A series of posts, [starting with this open letter](https://coveredinbees.org.archived.website/node/387.html) to protestors who proposed to destroy an experimental site of a publically funded UK research institute. The opening analogy: "We've decided Microsoft's corporate control over the computer world has gone too far. So we're coming to destroy your computers with a baseball bat. You're using open source software, you say? No matter: you're still using computers, and Microsoft make software for computers." It's not about GM tech, it's about who's using it. Anyone opposed to Monsanto-like global food system control should be supporting all publically funded GM research, not trashing it. Also, [some of the questions](https://coveredinbees.org.archived.website/node/393.html) I had following this episode, [discussion of how](https://coveredinbees.org.archived.website/node/388.html) different kinds of scientific ignorance map to different parts of the political spectrum and [analysis of the UK's green party leader's response](https://coveredinbees.org.archived.website/node/408.html) at the time. Oh and [a bunch of links](https://coveredinbees.org.archived.website/node/394.html), including some on the history of crop seed manipulation (including "irradiate to buggery and see what happens"). (Note: a couple of people I respect are still opposed to GM on precautionary grounds; I don't agree, but I try to remain open to civil disagreement on this, while also holding back strained anger that we need every possible tool to fight climate change, and this is a vital one.)
- **[Blood, sweat and containerisation](https://coveredinbees.org.archived.website/node/301.html)**: comparing two BBC programmes from 2010. One follows workers in a South-East Asian hard drive factory: "The workers are trained not to look up from their work regardless of what they hear. 'Every unit takes 3 seconds, a single glance takes 3 seconds,' points out the supervisor, 'so you will fail to meet your output.' " It follows one worker who returns home to see her two year old son, who no longer recognises her. The factory supervisor points out there are other options: scouring the local waste dump, or prostitution. Programme 2 examines the history of containerisation, which bought "value, choice and luxury beyond our wildest dreams." This global system – Krugman says, "The lofty moral tone of the opponents of globalization is possible only because they have chosen not to think their position through." Erm…
- **[Boiling stones, feeding cars](https://coveredinbees.org.archived.website/node/261.html)**: on the power and powerlessness of people who produce food. Contains this heartbreaking quote: "You don't see the day-to-day fear for the next day. In Brazil there's a custom, among the mothers in Northeastern Brazil in the shanty towns of the poverty-stricken states. When the children are crying with hunger in the evening, the mothers put a pan of water on the fire, put some stones in it and boil these stones. Then the mothers say: 'wait, wait, supper will be ready soon,' in the hope that their starving children will go to sleep, and stop crying in the meantime. That happens every day, repeated a thousand times." Relatedly, **[A toast to Karl Otrok](https://coveredinbees.org.archived.website/node/260.html)**: this post charts the transformation of a director of US seed company Pioneer in Romania, sliding from corporate figurehead to: "We \*\*\*\*d up the West, and now we're coming to Romania, and we'll fuck up all the agriculture here." Via documentary, [We Feed the World](https://en.wikipedia.org/wiki/We_Feed_the_World).

### Coveredinbees curiosities

- **[How many songs are there](https://coveredinbees.org.archived.website/node/264.html)**? A finite number. The calculations in my post [appeared in a VSauce video](https://youtu.be/DAcjV60RnRw?t=78) asking whether we'll ever run out of music.
- **[People vs petrol](https://coveredinbees.org.archived.website/node/344.html)**. Slightly flippant comparison of work done and cost of fossil fuel vs pedal power. "Diesel prices would have to increase a hundred-fold before human domestic power stations become a viable option."
- **[Why is a Romanesque](http://web.archive.org/web/20081120080738/https://www.danolner.net/v1/node/119)**? From an ancient blog incarnation: mulling the protien-interaction-geography miracle of the [perfect fractal cauliflower](http://web.archive.org/web/20081108114036/http://www.fourmilab.ch/images/Romanesco/).
- **["A gradual increase in the consuming power of the natives"](https://coveredinbees.org.archived.website/node/449.html)**: A quote from the general introduction to [The Resources of the Empire](http://en.wikipedia.org/wiki/The_British_Empire:_A_survey), from 1924, by [Sir Eric Geddes](http://en.wikipedia.org/wiki/Eric_Campbell_Geddes), a stark example of the ability to meld cold economic dominion and a sense of worthy purpose without breaking a sweat.
- **["Most businesses fail; high failure rate correlates to high innovation; attacking green investment failure dumb"](https://coveredinbees.org.archived.website/node/448.html)**: "A '5% increase in share of static firms = 1% lower annual TFP [technological frontier of production] growth'". So more stable firms in aggregate means less innovation overall.
- **[How 3D printing could change the spatial economy](https://coveredinbees.org.archived.website/node/412.html)** (if a Star-trek-level utopian version of it were achievable)
- **[Spuds and loops](https://coveredinbees.org.archived.website/node/383.html)**: a piece written for a local zine in 2012 connecting open source crop development to open source music making.
- **[How a climate "skeptic" asks for the time](https://coveredinbees.org.archived.website/node/351.html)**. (Written around the time of one of the various climate email nonsenses.)
- **["BBC causes mass jowel-shaking incident among the home counties! A-brbrbrbrbrrbbr!"](https://coveredinbees.org.archived.website/node/372.html)**
- **[Attacked by a limits to growth metaphor](https://coveredinbees.org.archived.website/node/314.html)**. That time a pigeon was a bit on the nose/beak (literally and metaphorically) while I was trying to write about how we often can't see economic/ecologic limits we're pushing until it's too late.
- **[The doughnut of empirical correctness](https://coveredinbees.org.archived.website/node/310.html)**. Is it a "monstrous perversion of science to claim that a theory is all the better for its shortcomings?" (Samuelson) Plus, bonus new philosophical object.
- **[Meat and symbols](https://coveredinbees.org.archived.website/node/277.html)**: various musings on the fact we're [made out of meat](https://youtu.be/T6JFTmQCFHg).
- **[private void alarmGoesOff](https://coveredinbees.org.archived.website/node/240.html)**: A very niche joke. A day in my PhD life, in the form of a short Java program.
- **[Marshall's questions](https://coveredinbees.org.archived.website/node/354.html)**. From Alfred Marshall's [Principles of Economics](https://www.econlib.org/library/Marshall/marP.html?chapter_num=5#book-reader) 1895. Contains some absolute gems. "How should we act so as to increase the good and diminish the evil influences of economic freedom, both in its ultimate results and in the course of its progress? If the first are good and the latter evil, but those who suffer the evil, do not reap the good; how far is it right that they should suffer for the benefit of others?" "Ought we to rest content with the existing forms of division of labour? Is it necessary that large numbers of the people should be exclusively occupied with work that has no elevating character?" "What are the proper relations of individual and collective action in a stage of civilization such as ours?" "Are the prevailing methods of using wealth entirely justifiable?" "Taking it for granted that a more equal distribution of wealth is to be desired…" Oh how quaint!
- **[A secret dictatorship has been ruling us all](https://coveredinbees.org.archived.website/node/357.html)**. "It is impossible to hide from, and has been controlling our lives for as long as humans have existed. Try to challenge it, and it will drop you from a great height. Its forces are everywhere, in every direction you can think of looking. It never, ever drops its guard. For centuries, people have fought an underground war against it, seeking to free themselves in whatever way they could. But whenever a crack is thought to be found, the forces are there again, slamming it shut. Democracies crumble before it, whole peoples are made to do its bidding. There is no hope of reprieve. There is no escape." (Belabouring a point: the physics of climate change is *physics* – it doesn't care if you deny its existence.)
- **[When the lights go out…](https://coveredinbees.org.archived.website/node/229.html)** "A young man related a recent tale from his hometown. One evening, early but already dark, there was a powercut. Showing no signs of ending, people lit candles, put them in jars and – after a while – started wandering out of their front doors. Chatting ensued. Chatting led to a large fire 'in an entirely inappropriate place'. A large musical band formed. Sometime after the music got going, some people in balaclavas clutching weapons turned up and asked if anyone fancied a fight. There was a thoughtful pause, broken eventually by a guitarist who starting singing, 'don't worry, be happy'. Everyone joined in. The storyteller didn't relate if that included the balaclava people. He ended with the question: "So, when the lights go out, what kind of anarchism will we have?"
