## Writing

Writing (and reading) is a very special part of being human. As well as my academic / technical / report stuff, I write about a range of topics (see posts [here](https://www.danolner.net/posts) and the [archive selection below](#best-of-coveredinbees)) and have also written a near future sci-fi book called "The Ink that Draws the Maps" (nice to get geography in there!) It's currently being rejected by agents, so most likely self-publishing soon. [More info on the book here](https://coveredinbees.org/posts/i_wrote_a_scifi_book/).

Writing community has become essential to me. I'm part of [Sheffield's wonderful Writers' Workshop](https://www.thewritersworkshop.co.uk/) and [Lisa Munro](https://www.lisamunro.net/)'s more American-leaning group (without which the sci-fi book would never have been finished).

Most of my academic writing is linked in the project list above; here's my [Google scholar](https://scholar.google.com/citations?user=a8u6oo0AAAAJ&hl=en&oi=ao) page for the small remainder.
