project:
  type: website
  output-dir: docs
  resources:
  - CNAME

website:
  title: "danolner_dot_net"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - yeti
    fontsize: 1.2em
    linestretch: 1.7
    css: styles.css
    toc: true



